// <auto-generated />
using System;
using Blog.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blog.Server.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20190403144823_AddedImageUrl")]
    partial class AddedImageUrl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blog.Shared.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Post");

                    b.Property<DateTime>("Posted");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new { Id = 1, Author = "Joe Bloggs", ImageUrl = "~/img/broken-egg.jpg", Post = "This is a sample blog post.", Posted = new DateTime(2019, 4, 3, 15, 48, 23, 254, DateTimeKind.Local), Title = "Sample Post Title" },
                        new { Id = 2, Author = "Joe Cloggs", ImageUrl = "~/img/chalk.jpg", Post = "2 This is a sample blog post.", Posted = new DateTime(2019, 4, 2, 15, 48, 23, 256, DateTimeKind.Local), Title = "Sample Post Title 2" },
                        new { Id = 3, Author = "Joe Doggs", ImageUrl = "~/img/glass.jpg", Post = "3 This is a sample blog post.", Posted = new DateTime(2019, 4, 1, 15, 48, 23, 256, DateTimeKind.Local), Title = "Sample Post Title 3" },
                        new { Id = 4, Author = "Joe Eloggs", ImageUrl = "~/img/hammer.jpg", Post = "4 This is a sample blog post.", Posted = new DateTime(2019, 3, 31, 15, 48, 23, 256, DateTimeKind.Local), Title = "Sample Post Title 4" },
                        new { Id = 5, Author = "Joe Floggs", ImageUrl = "~/img/robot.jpg", Post = "5 This is a sample blog post.", Posted = new DateTime(2019, 3, 30, 15, 48, 23, 256, DateTimeKind.Local), Title = "Sample Post Title 5" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
